apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: simple-go-api
  name: simple-go-api
spec:
  containers:
  - image: enzoaliatis/simple-service-golang:latest
    name: simple-go-api
    ports:
    - containerPort: 8080
      name: http
    resources:
      limits:
        cpu: 50m
        memory: 32Mi
      requests:
        cpu: 50m
        memory: 32Mi
    livenessProbe:
      httpGet:
        path: /health
        port: http
    readinessProbe:
      httpGet:
        path: /health
        port: http
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
